### ISSUE TITLE
BUG the externalconfig.txt is default

### ISSUE THREAD

**Issue by thesamir** [Soartex/Texture-Patcher-v1#54]
when i try to opent up the .jar, it says ERROR externalconfig.txt is default and it creates a file named texturepatcher-1.2.log and then it says:

[18:20:13] [SEVERE] The externalconfig.txt file is the default!
net.soartex.texture_patcher.Texture_Patcher_Exception: The externalconfig.txt file is the default!
    at net.soartex.texture_patcher.Texture_Patcher.loadConfig(Texture_Patcher.java:316)
    at net.soartex.texture_patcher.Texture_Patcher.run(Texture_Patcher.java:137)
    at java.lang.Thread.run(Thread.java:744)

**Comment by artdude543** [comment]
Hey, please make sure you are using the patcher from here http://soartex.net/downloads/ At the moment the mods will not download I am working on the fix for it now.

**Comment by hron84** [comment]
@artdude543 i use patcher from there, still same issue. Please reopen this bug report.

**Comment by artdude543** [comment]
The download on the site does work hence why we added it to the site downloads, make sure you have the latest version of which can be found here: http://soartex.net/downloads/mods/

**Comment by hron84** [comment]
I downloaded the latest linked version on the site again, still not works.
Could you please provide details what is this file and where it searches? I
use Linux OS so it can be the problem...
2014.10.18. 18:17 ezt írta ("Kieron Richardson" notifications@github.com):

**Comment by ghost** [comment]
Linux isn't a problem at all, running Deb Jessie with the version posted above working fine.

**Comment by goldbattle** [comment]
Can you make sure that the file that you are running is `Soartex-Patcher-2.4.jar` and **not** `Texture-Patcher-2.4.jar`

If there are anymore details you can give us that would be great, for example your java version and how you are running the file.

**Comment by hron84** [comment]
I tried to download from http://soartex.net/downloads/mods/ (I belived it's same as https://soartex.net/patcher/) and it seems working now.

However this is really confusing, webpage does not help for user to find the right software. As a new patcher user, I have no way to tell there is two different thing without browsing the whole site. Maybe a separated site for the generic patcher would solve this problem. Or, at least a warning on generic patcher's page with text "This is a generic patcher software. If you finding Soartex-specific Texture Patcher, click here". Ppl coming from Google possibly lands on soartex.net/patcher/ because it is the shorter and Google prefers URLs with keywords over than URL without keyword.

**Comment by goldbattle** [comment]
Yes, you are indeed correct. In fact those downloads are different, the ones on the patcher page are meant for other texturepack artist to use to leverage the power of our application.

We already had a reworked page in the works when you brought this issue back up. The revised page will roll out sometime today, and should clarify things a bit more. Thanks for bringing this up to us.
