### ISSUE TITLE
Soartex-Patcher-2.2 error

### ISSUE THREAD

**Issue by Goten87** [Soartex/Texture-Patcher-v1#57]
having a error if i try to open Soartex-Patcher-2.2
`A java exception had occurred`
running java JDK 1.8.0_05 64Bit (os: Windows7 ulti)

Soartex-Patcher-2.1 is working fine for me and that need java 7

**Comment by cathode** [comment]
I'm getting the same error, here's the stack trace.

C:\minecraft\gs172\textures>java -jar Texture-Patcher-2.2.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/soartex/t
exture_patcher/TexturePatcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by ShadowG0D** [comment]
Also Having same issue. :(

**Comment by thatcraniumguy** [comment]
@cathode: Your issue is the version Java you're using. Apparently the 2.2 version only supports Java 8. Which you can get from here: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

But I'm also having an issue, because it requires an externalconfig.txt as well...and that's not autogenerated.

**Comment by ghost** [comment]
@craniumguy It seems like you have to host your own config.json (and branches.json) now, since cloudfare is blocking the requests from the patcher due their "human check". Don't know if that's intended or not. 

In the meantime I got a gradle based fork up and running with a explanation in the README, maybe you  can get it running there: https://github.com/Chefeification/Texture-Patcher

If there are any problems with the fork use the Issue tracker there.

**Comment by artdude543** [comment]
We are aware of the problem regarding CloudFlare we are in the works with a fix but this will take time to do so. This was a problem we never expected to encounter but the bug was found a few hours are the server relocation and a fix was started then. We expect it to be working again at a maximum of a week to 2 weeks. Due to our provider having a holiday so contact with them is scarce at the moment.

**Comment by ghost** [comment]
@artdude543 Good to hear ;)

**Comment by artdude543** [comment]
Will be uploading a new build in a few mins

**Comment by artdude543** [comment]
And here it be the release contains the customizable version and this download is for the Fanver version http://dl.soartex.net/1gakr

**Comment by ghost** [comment]
@artdude543 I got switched to okhttp (witch fixes the cloudfare thingy due its user agent setting) and head requests for file checks, it loads _quite_ faster now. Maybe we should consider a merge?

**Comment by artdude543** [comment]
Hmm, leme talk to the other developers we are planning on re-making the whole patcher system at some point but your idea does sound a bit better than the current "hackish" way I have the bug fixed.
