### ISSUE TITLE
Re-patching resource packs

### ISSUE THREAD

**Issue by hron84** [Soartex/Texture-Patcher-v1#60]
It would be good if patcher can determine and mark (with colors) already included mods in patched texture packs. This can be achieved via extending the current modslist.csv with version numbers and parsing it in the patcher. It would be better if patcher can pre-select upgraded mods to re-patch the zip.

Also, I recommend you to replace the csv with a bit smarter Java MANIFEST.MF file, because you can add more properties to it.

**Comment by goldbattle** [comment]
It actually already does. When you select a pack, and then check for updates, it highlights those packs installed as yellow. The current 'see if that patch is outdated' has been broken for a while because of how we generate the zips now. When it is outdated, it gets highlighted in red, and gets auto checked for easy updating. What am i missing here?

![0c5115a6-7c75-11e4-833d-869f59213810](https://cloud.githubusercontent.com/assets/2222562/5321715/e947b738-7c8b-11e4-8392-5df4770347bd.png)

In the future iteration of the patcher, the format of choice will be json.

**Comment by hron84** [comment]
@goldbattle I did not noticed the yellow marking, maybe because it not too visible color. I'll check it, but i recommend you some more visible color, like light blue, and also changing the background of the whole row instead of bordering the mod name, because bordering is not too noticable.

I could not test outdated packages from obvious reason: I installed the patcher right now (yesterday) and there is no upgraded package yet. However, I recommend you to check the upgraded packages automagically or provide a menu entry to do auto-check to make upgrading easier.
